# Sample configuration
samples:
  sample_list: "/data/humangen_kircherlab/Users/hassan/repos/sandbox_launchpad/snakeotate/resources/batch_lists/batch_1_sample_list.csv"
  
base_dir: "snakeotate/samples"

thresholds:  # Fixed: was "threasholds"
  af_threshold: 0.005
  cadd_threshold: 20